package org.user.app.model;

import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;
import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.Min;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Pattern;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Represents an employee entity in the system.
 */
@Document(collection = "employees")
@Data
@NoArgsConstructor
public class Employee {
    
    /**
     * The unique identifier for the employee.
     * Automatically generated by MongoDB.
     */
    @Id
    private String id;
    
    /**
     * The first name of the employee.
     * This field is mandatory and cannot be blank.
     */
    @NotBlank(message = "Name is mandatory")
    private String firstName;
    
    /**
     * The last name of the employee.
     * This field is optional and can be left blank.
     */
    private String lastName;
    
    /**
     * The email address of the employee.
     * This field is mandatory and must be a valid email format.
     */
    @NotBlank(message = "Email is mandatory")
    @Email(message = "Incorrect email format")
    private String email;
    
    /**
     * The phone number of the employee.
     * This field must be exactly 10 digits long.
     */
    @Pattern(regexp = "\\d{10}", message = "Phone number must be exactly 10 digits")
    private String phoneNo;
    
    /**
     * The salary of the employee.
     * This field must be greater than 1.
     */
    @Min(value = 1, message = "Salary must be greater than 1")
    private long salary;
    
    /**
     * The department to which the employee belongs.
     * This field is mandatory and cannot be blank.
     */
    @NotBlank(message = "Department must be assigned")
    private String department;
    
    
    /**
     * The role of the employee within the organization.
     * This field is mandatory and cannot be blank.
     */
    @NotBlank(message = "Role is mandatory")
    private String role;
    
    /**
     * The Location of the employee .
     * This field is mandatory and cannot be blank.
     */
    @NotBlank(message = "Location must be assigned")
    private String location;
    
}
